name: Exportar modpack

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Instalar Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refrescar índice
        working-directory: ./Packwiz
        run: packwiz refresh

      - name: Exportar para Modrinth
        working-directory: ./Packwiz
        run: packwiz modrinth export -o ../Potatously-Optimized-${{ github.event.release.tag_name }}.mrpack

      - name: Subir .mrpack a la release
        uses: softprops/action-gh-release@v2
        with:
          files: Potatously-Optimized-${{ github.event.release.tag_name }}.mrpack